name: TriggerRelease

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          METADATA="$(cargo metadata --format-version=1 --no-deps)"
          VERSION="$(echo $METADATA | jq -r '.packages[0].version')"
          echo "VERSION: $VERSION"
          TAGNAME="v$VERSION"
          echo "TAGNAME: $TAGNAME"
          git tag $TAGNAME
          git push origin $TAGNAME
